# Generated by Django 2.2.3 on 2019-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190512_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimg',
            field=models.CharField(db_column='userImg', default='md.ipg', max_length=50),
        ),
    ]
