# Generated by Django 2.2.3 on 2019-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_userimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangerUser',
            fields=[
                ('muserid', models.CharField(db_column='MuserId', max_length=45, primary_key=True, serialize=False)),
                ('musername', models.CharField(db_column='MuserName', max_length=50, unique=True)),
                ('muserphonenum', models.CharField(db_column='MuserPhoneNum', max_length=11, unique=True)),
                ('mpassword', models.CharField(db_column='Mpassword', max_length=50)),
            ],
            options={
                'db_table': 'MangerUser',
                'managed': True,
            },
        ),
    ]
