# Generated by Django 2.2.3 on 2019-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mangeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userintroduction',
            field=models.CharField(db_column='userIntroduction', default='22', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='userlastlogintime',
            field=models.DateTimeField(db_column='userLastlogintime', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usersex',
            field=models.IntegerField(db_column='userSex', default=0),
        ),
    ]
