# Generated by Django 2.2.3 on 2019-08-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190810_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantShow',
            fields=[
                ('spid', models.CharField(db_column='spID', max_length=45, primary_key=True, serialize=False)),
                ('spname', models.CharField(db_column='spName', default='123', max_length=45)),
                ('spintrc', models.CharField(db_column='spIntrc', default='eafef', max_length=255)),
                ('spmark', models.CharField(db_column='spMark', default='23', max_length=45)),
                ('spplantstime', models.DateField(auto_now=True, db_column='spPlantstime')),
                ('spplantetime', models.DateField(auto_now=True, db_column='spPlantetime')),
                ('spheat', models.CharField(db_column='spHeat', default='32', max_length=45)),
                ('incubator_incuno', models.ForeignKey(blank=True, db_column='Incubator_IncuNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Incubator')),
            ],
            options={
                'db_table': 'plantshow',
                'managed': True,
            },
        ),
    ]
