# Generated by Django 2.2.3 on 2019-08-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_incplantdetail_incubatorhardinf_usershowlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selldetail',
            fields=[
                ('sdid', models.CharField(db_column='sdID', max_length=45, primary_key=True, serialize=False)),
                ('sddate', models.DateField(auto_now=True, db_column='sdDate')),
                ('mostsellperson', models.CharField(db_column='mostsellPerson', max_length=45, null=True)),
                ('mostsellInc', models.CharField(db_column='mostsellInc', max_length=45, null=True)),
                ('mostsellarea', models.CharField(db_column='mostsellarea', max_length=45, null=True)),
            ],
            options={
                'db_table': 'selldetail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(db_column='areaName', max_length=45, null=True)),
                ('managername', models.CharField(db_column='managerName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'sellmanager',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='incplantdetail',
            name='incplantdetaildate',
            field=models.DateField(auto_now=True, db_column='incplantdetailDate'),
        ),
        migrations.AddField(
            model_name='incubator',
            name='managerstage',
            field=models.CharField(db_column='managerStage', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='incubator',
            name='usetime',
            field=models.IntegerField(db_column='useTime', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pavermark',
            field=models.IntegerField(db_column='paverMark', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pplantaverpeople',
            field=models.IntegerField(db_column='pplantaverPeople', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pplantavertime',
            field=models.IntegerField(db_column='pplantaverTime', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pplantsumpeople',
            field=models.IntegerField(db_column='pplantsumPeople', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pplantsumtime',
            field=models.IntegerField(db_column='pplantsumTime', null=True),
        ),
        migrations.CreateModel(
            name='Fixinfo',
            fields=[
                ('fixinfoid', models.CharField(db_column='fixinfoID', max_length=45, primary_key=True, serialize=False)),
                ('ifover', models.IntegerField(db_column='ifOver', null=True)),
                ('fixmanager', models.CharField(db_column='fixManager', max_length=45, null=True)),
                ('fixputdate', models.DateField(auto_now=True, db_column='fixputDate')),
                ('incubator_incuno', models.ForeignKey(blank=True, db_column='Incubator_IncuNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Incubator')),
                ('user_userid', models.ForeignKey(blank=True, db_column='User_userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
            options={
                'db_table': 'fixinfo',
                'managed': True,
            },
        ),
    ]
